### ISSUE TITLE
Ruby version

### ISSUE THREAD

**Issue by MckinstryJ** [TravisGM92/webparser#2]
Yo can you upgrade your ruby to 2.7.2

Also... when you're free... could you show me around your code.

Some questions I have:
- Where is it parsing the website pages?
- Where is it storing the data to the database?
- How do you view that info?
- etc.

**Comment by TravisGM92** [comment]
> Yo can you upgrade your ruby to 2.7.2
> 
> Also... when you're free... could you show me around your code.
> 
> Some questions I have:
> 
> * Where is it parsing the website pages?
> * Where is it storing the data to the database?
> * How do you view that info?
> * etc.

Do you need me to upgrade the Ruby version in the app as well?

**Comment by MckinstryJ** [comment]
I'm assuming yes. This is my gem file:

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

gem 'rails', '~> 6.1.3', '>= 6.1.3.1'
gem 'sqlite3', '~> 1.4'
gem 'puma', '~> 5.0'
gem 'sass-rails', '>= 6'
gem 'webpacker', '~> 5.0'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.7'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'devise', '~> 4.7', '>= 4.7.3'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'web-console', '>= 4.1.0'
  gem 'rack-mini-profiler', '~> 2.0'
end

group :test do
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver'
  gem 'webdrivers'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
